// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_Counter;
lv_obj_t * ui_ScreenSetup;
lv_obj_t * ui_PanelEdit;
lv_obj_t * ui_itemLblEdit;
lv_obj_t * ui_Image1;
lv_obj_t * ui_PanelOptions;
lv_obj_t * ui_itemLblOptions;
lv_obj_t * ui_Image2;
lv_obj_t * ui_PanelEditRGB;
lv_obj_t * ui_itemLblRGB;
lv_obj_t * ui_Image3;
lv_obj_t * ui_ScreenEdit;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_valueLbl1;
lv_obj_t * ui_value1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_valueLbl2;
lv_obj_t * ui_value2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_valueLbl3;
lv_obj_t * ui_value3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_valueLbl4;
lv_obj_t * ui_value4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_valueLbl5;
lv_obj_t * ui_value5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_valueLbl6;
lv_obj_t * ui_value6;
lv_obj_t * ui_ScreenOptions;
lv_obj_t * ui_PanelEditHID;
lv_obj_t * ui_CheckboxHID;
lv_obj_t * ui_PanelEditMount;
lv_obj_t * ui_CheckboxMount;
lv_obj_t * ui_ScreenEditRGB;
lv_obj_t * ui_PanelRed;
lv_obj_t * ui_valueLblRed;
lv_obj_t * ui_valueRed;
lv_obj_t * ui_PanelGreen;
lv_obj_t * ui_valueLblGreen;
lv_obj_t * ui_valueGreen;
lv_obj_t * ui_PanelBlue;
lv_obj_t * ui_valueLblBlue;
lv_obj_t * ui_valueBlue;
lv_obj_t * ui_PanelButtons;
lv_obj_t * ui_ButtonOK;
lv_obj_t * ui_valueLblOK;
lv_obj_t * ui_ButtonWHITE;
lv_obj_t * ui_valueLblWHITE;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_155062242[1] = {&ui_img_749525677};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Counter = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Counter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Counter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Counter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Counter, "0");
    lv_obj_set_style_text_font(ui_Counter, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

}
void ui_ScreenSetup_screen_init(void)
{
    ui_ScreenSetup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenSetup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenSetup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenSetup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenSetup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenSetup, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEdit = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelEdit, lv_pct(100));
    lv_obj_set_height(ui_PanelEdit, lv_pct(22));
    lv_obj_set_align(ui_PanelEdit, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelEdit, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelEdit, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelEdit, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelEdit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelEdit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelEdit, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelEdit, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_itemLblEdit = lv_label_create(ui_PanelEdit);
    lv_obj_set_width(ui_itemLblEdit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itemLblEdit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_itemLblEdit, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_itemLblEdit, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_itemLblEdit, "Edit Variables");
    lv_obj_set_style_border_color(ui_itemLblEdit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_itemLblEdit, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_itemLblEdit, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image1 = lv_img_create(ui_PanelEdit);
    lv_img_set_src(ui_Image1, &ui_img_749525677);
    lv_obj_set_width(ui_Image1, 16);
    lv_obj_set_height(ui_Image1, 16);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelOptions = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelOptions, lv_pct(100));
    lv_obj_set_height(ui_PanelOptions, lv_pct(22));
    lv_obj_set_align(ui_PanelOptions, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelOptions, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelOptions, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelOptions, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelOptions, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelOptions, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelOptions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelOptions, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelOptions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelOptions, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelOptions, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_itemLblOptions = lv_label_create(ui_PanelOptions);
    lv_obj_set_width(ui_itemLblOptions, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itemLblOptions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_itemLblOptions, LV_ALIGN_CENTER);
    lv_label_set_text(ui_itemLblOptions, "App Options");
    lv_obj_set_style_border_color(ui_itemLblOptions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_itemLblOptions, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_itemLblOptions, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image2 = lv_img_create(ui_PanelOptions);
    lv_img_set_src(ui_Image2, &ui_img_749525677);
    lv_obj_set_width(ui_Image2, 16);
    lv_obj_set_height(ui_Image2, 16);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelEditRGB = lv_obj_create(ui_ScreenSetup);
    lv_obj_set_width(ui_PanelEditRGB, lv_pct(100));
    lv_obj_set_height(ui_PanelEditRGB, lv_pct(22));
    lv_obj_set_align(ui_PanelEditRGB, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelEditRGB, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelEditRGB, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelEditRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelEditRGB, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelEditRGB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelEditRGB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelEditRGB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelEditRGB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelEditRGB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelEditRGB, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_itemLblRGB = lv_label_create(ui_PanelEditRGB);
    lv_obj_set_width(ui_itemLblRGB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_itemLblRGB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_itemLblRGB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_itemLblRGB, "RGB Led ");
    lv_obj_set_style_border_color(ui_itemLblRGB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_itemLblRGB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_itemLblRGB, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Image3 = lv_img_create(ui_PanelEditRGB);
    lv_img_set_src(ui_Image3, &ui_img_749525677);
    lv_obj_set_width(ui_Image3, 16);
    lv_obj_set_height(ui_Image3, 16);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
void ui_ScreenEdit_screen_init(void)
{
    ui_ScreenEdit = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_ScreenEdit, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenEdit, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenEdit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenEdit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenEdit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel1, lv_pct(92));
    lv_obj_set_height(ui_Panel1, lv_pct(24));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_valueLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl1, "Value 1: ");

    ui_value1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_value1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value1, 117);
    lv_obj_set_y(ui_value1, -33);
    lv_obj_set_align(ui_value1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value1, "150");
    lv_label_set_recolor(ui_value1, "true");

    ui_Panel2 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel2, lv_pct(92));
    lv_obj_set_height(ui_Panel2, lv_pct(24));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_valueLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl2, "Value 2: ");

    ui_value2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_value2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value2, 117);
    lv_obj_set_y(ui_value2, -33);
    lv_obj_set_align(ui_value2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value2, "1500");
    lv_label_set_recolor(ui_value2, "true");

    ui_Panel3 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel3, lv_pct(92));
    lv_obj_set_height(ui_Panel3, lv_pct(24));
    lv_obj_set_x(ui_Panel3, 5);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_valueLbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl3, "Value 3: ");

    ui_value3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_value3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value3, 117);
    lv_obj_set_y(ui_value3, -33);
    lv_obj_set_align(ui_value3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value3, "36.5");
    lv_label_set_recolor(ui_value3, "true");

    ui_Panel4 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel4, lv_pct(92));
    lv_obj_set_height(ui_Panel4, lv_pct(24));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_valueLbl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl4, "Value 4: ");

    ui_value4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_value4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value4, 117);
    lv_obj_set_y(ui_value4, -33);
    lv_obj_set_align(ui_value4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value4, "25.63");
    lv_label_set_recolor(ui_value4, "true");

    ui_Panel5 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel5, lv_pct(92));
    lv_obj_set_height(ui_Panel5, lv_pct(24));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_valueLbl5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLbl5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl5, "Value 5: ");

    ui_value5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_value5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value5, 117);
    lv_obj_set_y(ui_value5, -33);
    lv_obj_set_align(ui_value5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value5, "true");
    lv_label_set_recolor(ui_value5, "true");

    ui_Panel6 = lv_obj_create(ui_ScreenEdit);
    lv_obj_set_width(ui_Panel6, lv_pct(92));
    lv_obj_set_height(ui_Panel6, lv_pct(24));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLbl6 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_valueLbl6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLbl6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueLbl6, 0);
    lv_obj_set_y(ui_valueLbl6, -1);
    lv_obj_set_align(ui_valueLbl6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLbl6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLbl6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLbl6, "Value 6: ");

    ui_value6 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_value6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value6, 117);
    lv_obj_set_y(ui_value6, -33);
    lv_obj_set_align(ui_value6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value6, "true");
    lv_label_set_recolor(ui_value6, "true");

}
void ui_ScreenOptions_screen_init(void)
{
    ui_ScreenOptions = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenOptions, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenOptions, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenOptions, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenOptions, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenOptions, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenOptions, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenOptions, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenOptions, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenOptions, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEditHID = lv_obj_create(ui_ScreenOptions);
    lv_obj_set_width(ui_PanelEditHID, lv_pct(100));
    lv_obj_set_height(ui_PanelEditHID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelEditHID, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelEditHID, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelEditHID, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelEditHID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelEditHID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelEditHID, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelEditHID, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEditHID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEditHID, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEditHID, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelEditHID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelEditHID, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelEditHID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelEditHID, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelEditHID, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CheckboxHID = lv_checkbox_create(ui_PanelEditHID);
    lv_checkbox_set_text(ui_CheckboxHID, "USB KEYPAD");
    lv_obj_set_width(ui_CheckboxHID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxHID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxHID, 387);
    lv_obj_set_y(ui_CheckboxHID, -44);
    lv_obj_set_align(ui_CheckboxHID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxHID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_CheckboxHID, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CheckboxHID, 255, LV_PART_INDICATOR | LV_STATE_FOCUSED);

    ui_PanelEditMount = lv_obj_create(ui_ScreenOptions);
    lv_obj_set_width(ui_PanelEditMount, lv_pct(100));
    lv_obj_set_height(ui_PanelEditMount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelEditMount, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelEditMount, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelEditMount, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelEditMount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelEditMount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelEditMount, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelEditMount, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEditMount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEditMount, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEditMount, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelEditMount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelEditMount, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelEditMount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelEditMount, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelEditMount, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CheckboxMount = lv_checkbox_create(ui_PanelEditMount);
    lv_checkbox_set_text(ui_CheckboxMount, "Mount Device");
    lv_obj_set_width(ui_CheckboxMount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxMount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxMount, 387);
    lv_obj_set_y(ui_CheckboxMount, -44);
    lv_obj_set_align(ui_CheckboxMount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxMount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_CheckboxMount, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CheckboxMount, 255, LV_PART_INDICATOR | LV_STATE_FOCUSED);

}
void ui_ScreenEditRGB_screen_init(void)
{
    ui_ScreenEditRGB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEditRGB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenEditRGB, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenEditRGB, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_ScreenEditRGB, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenEditRGB, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenEditRGB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenEditRGB, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenEditRGB, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenEditRGB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRed = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelRed, lv_pct(100));
    lv_obj_set_height(ui_PanelRed, lv_pct(25));
    lv_obj_set_x(ui_PanelRed, 5);
    lv_obj_set_y(ui_PanelRed, 0);
    lv_obj_set_align(ui_PanelRed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelRed, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelRed, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelRed, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelRed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelRed, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelRed, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblRed = lv_label_create(ui_PanelRed);
    lv_obj_set_width(ui_valueLblRed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblRed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblRed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblRed, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblRed, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblRed, "Red: ");

    ui_valueRed = lv_label_create(ui_PanelRed);
    lv_obj_set_width(ui_valueRed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueRed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueRed, 117);
    lv_obj_set_y(ui_valueRed, -33);
    lv_obj_set_align(ui_valueRed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueRed, "60");
    lv_label_set_recolor(ui_valueRed, "true");

    ui_PanelGreen = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelGreen, lv_pct(100));
    lv_obj_set_height(ui_PanelGreen, lv_pct(25));
    lv_obj_set_align(ui_PanelGreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelGreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelGreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelGreen, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelGreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelGreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelGreen, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelGreen, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblGreen = lv_label_create(ui_PanelGreen);
    lv_obj_set_width(ui_valueLblGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblGreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblGreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblGreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblGreen, "Green: ");

    ui_valueGreen = lv_label_create(ui_PanelGreen);
    lv_obj_set_width(ui_valueGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueGreen, 117);
    lv_obj_set_y(ui_valueGreen, -33);
    lv_obj_set_align(ui_valueGreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueGreen, "10");
    lv_label_set_recolor(ui_valueGreen, "true");

    ui_PanelBlue = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelBlue, lv_pct(100));
    lv_obj_set_height(ui_PanelBlue, lv_pct(25));
    lv_obj_set_align(ui_PanelBlue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelBlue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelBlue, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelBlue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBlue, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBlue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBlue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBlue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelBlue, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelBlue, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblBlue = lv_label_create(ui_PanelBlue);
    lv_obj_set_width(ui_valueLblBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblBlue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblBlue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblBlue, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblBlue, "Blue: ");

    ui_valueBlue = lv_label_create(ui_PanelBlue);
    lv_obj_set_width(ui_valueBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valueBlue, 117);
    lv_obj_set_y(ui_valueBlue, -33);
    lv_obj_set_align(ui_valueBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueBlue, "true");
    lv_label_set_recolor(ui_valueBlue, "true");

    ui_PanelButtons = lv_obj_create(ui_ScreenEditRGB);
    lv_obj_set_width(ui_PanelButtons, lv_pct(100));
    lv_obj_set_height(ui_PanelButtons, lv_pct(25));
    lv_obj_set_align(ui_PanelButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelButtons, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelButtons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelButtons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelButtons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PanelButtons, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_PanelButtons, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ButtonOK = lv_btn_create(ui_PanelButtons);
    lv_obj_set_width(ui_ButtonOK, 40);
    lv_obj_set_height(ui_ButtonOK, 16);
    lv_obj_set_align(ui_ButtonOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOK, lv_color_hex(0xE9A047), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonOK, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblOK = lv_label_create(ui_ButtonOK);
    lv_obj_set_width(ui_valueLblOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblOK, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblOK, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblOK, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblOK, "OK");

    ui_ButtonWHITE = lv_btn_create(ui_PanelButtons);
    lv_obj_set_width(ui_ButtonWHITE, 80);
    lv_obj_set_height(ui_ButtonWHITE, 16);
    lv_obj_set_align(ui_ButtonWHITE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonWHITE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWHITE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonWHITE, lv_color_hex(0xE9A047), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonWHITE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_valueLblWHITE = lv_label_create(ui_ButtonWHITE);
    lv_obj_set_width(ui_valueLblWHITE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valueLblWHITE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_valueLblWHITE, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valueLblWHITE, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_valueLblWHITE, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_valueLblWHITE, "WHITE");

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMain_screen_init();
    ui_ScreenSetup_screen_init();
    ui_ScreenEdit_screen_init();
    ui_ScreenOptions_screen_init();
    ui_ScreenEditRGB_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMain);
}
