// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_SimpleMenu

#ifndef _SQUARELINE_SIMPLEMENU_UI_H
#define _SQUARELINE_SIMPLEMENU_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_Counter;
extern lv_obj_t * ui_ScreenSetup;
extern lv_obj_t * ui_PanelEdit1;
extern lv_obj_t * ui_itemLbl1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_PanelEdit2;
extern lv_obj_t * ui_itemLbl2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_PanelEditRGB;
extern lv_obj_t * ui_itemLblRGB;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_PanelEdit4;
extern lv_obj_t * ui_CheckboxHID;
extern lv_obj_t * ui_ScreenEdit1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_valueLbl1;
extern lv_obj_t * ui_value1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_valueLbl2;
extern lv_obj_t * ui_value2;
extern lv_obj_t * ui_ScreenEdit2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_valueLbl3;
extern lv_obj_t * ui_value3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_valueLbl4;
extern lv_obj_t * ui_value4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_valueLbl5;
extern lv_obj_t * ui_value5;
extern lv_obj_t * ui_ScreenEditRGB;
extern lv_obj_t * ui_PanelRed;
extern lv_obj_t * ui_valueLblRed;
extern lv_obj_t * ui_valueRed;
extern lv_obj_t * ui_PanelGreen;
extern lv_obj_t * ui_valueLblGreen;
extern lv_obj_t * ui_valueGreen;
extern lv_obj_t * ui_PanelBlue;
extern lv_obj_t * ui_valueLblBlue;
extern lv_obj_t * ui_valueBlue;
extern lv_obj_t * ui_PanelButtons;
extern lv_obj_t * ui_ButtonOK;
extern lv_obj_t * ui_valueLblOK;
extern lv_obj_t * ui_ButtonWHITE;
extern lv_obj_t * ui_valueLblWHITE;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_749525677);    // assets\Arrows-Right2-16.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
